---
title: "RShiny"
author: "C.J. Angrisani"
date: "February 28, 2019"
output: html_document
runtime: shiny
---

```{r}

library(scales)
library(shiny)

turtles <- read.table("Turtle Blood Gas Data.txt", header = TRUE, fill = TRUE, sep = "\t", na.strings = "NA")
t_surv <- subset(turtles, !is.na(survival))

ui <- fluidPage(

  headerPanel("Turtle Survival"),
  
  mainPanel(
    tableOutput("values"),
    #uiOutput("focal"),
    tabsetPanel(type = "tabs",
                  tabPanel("Sliders",
                           sidebarPanel(
                                        sliderInput("PCV", "PCV:", min = 0, max = 50, value = 25, step = 0.1),
                                        sliderInput("Glu", "Glu:", min = 0, max = 600, value = 300)
                            ),
                           mainPanel(height = "1000px",
                                     p("The probability that the turtle survives is:"),
                                     verbatimTextOutput("sliders"),
                                     column(4, imageOutput("image"))
                           )
                  ),
                  tabPanel("Regression",
                           mainPanel(
                                     p("Final regression used to calculate probability."),
                                     verbatimTextOutput(outputId = "fit"),
                                     width = 25
                                  
                           )
                  )
    )
  )

)

server <- function(input, output) {

  sliderValues <- reactive({

    data.frame(
      Name = c("PCV",
               "Glu"
               ),
      Value = as.character(c(input$PCV,
                             input$Glu
                             )), 
      stringsAsFactors=FALSE)
  }) 
  
  logit2prob <- function(PCV, Glu){
      logp <- -1.3313 + 0.2396*PCV + -0.0153*Glu
      prat <- exp(logp)
      prob <- prat / (1 + prat)
      return(prob*100)
  }
  
  mylogit <- glm(survival ~ PCV + Glu, family = "binomial", data = t_surv)
  
  output$sliders <- renderText(
    {
      logit2prob(input$PCV, input$Glu)
    }
  )
  
  output$fit <- renderPrint(
    summary(mylogit)
  )
  
  output$image <- renderImage({

    if(logit2prob(input$PCV, input$Glu) >= 50){
      list(
        src = "happy squirtle.png",
        contentType = "image/png",
        alt = "Happy"
      )
    }
    else{
      list(
        src = "sad squirtle.png",
        contenttype = "image/png",
        alt = "Sad"
      )
    }
  }, deleteFile = FALSE)
  
}

```


```{r}

shinyApp(ui, server)

```
